// Generated by eve. Do not edit by hand.
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/internal/workflow/builtins.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/.eve/dev-runtime/snapshots/mqxx8qns-e71b9120-35a8-4a7b-b96c-8489b1830e30/source/.eve/compile/compiled-artifacts-bootstrap.mjs";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/create-session-step.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/delegated-parent-notification.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/dispatch-runtime-actions-step.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/dispatch-workflow-runtime-actions-step.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/durable-session-store.d.ts";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/forward-turn-delivery-step.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/route-child-delivery.d.ts";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/session-callback-step.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/subagent-adapter.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/turn-control-protocol.js";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/workflow-entry.d.ts";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/workflow-steps.d.ts";
import "file:///C:/Users/sharm/OneDrive/Documents/personal-projects/Precedent/node_modules/eve/dist/src/execution/workflow-steps.js";
export const __steps_registered = true;
