// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/tools/diff_parser.ts";
import * as module_2 from "../../agent/tools/github_fetcher.ts";
import * as module_3 from "../../agent/tools/markdown_exporter.ts";
import * as module_4 from "../../agent/tools/memory_consistency_checker.ts";
import * as module_5 from "../../agent/tools/repository_scanner.ts";
import * as module_6 from "../../agent/tools/review_analyzer.ts";
import * as module_7 from "../../agent/tools/timeline_generator.ts";
import * as module_8 from "../../agent/subagents/assumption_hunter/agent.ts";
import * as module_9 from "../../agent/subagents/knowledge_validator/agent.ts";
import * as module_10 from "../../agent/subagents/maintainer/agent.ts";
import * as module_11 from "../../agent/subagents/mergeability_gate/agent.ts";
import * as module_12 from "../../agent/subagents/pr_reviewer/agent.ts";
import * as module_13 from "../../agent/subagents/repo_expert/agent.ts";
import * as module_14 from "../../agent/subagents/test_gap/agent.ts";
import * as module_15 from "../../agent/subagents/wiki_architect/agent.ts";
import * as module_16 from "../../agent/subagents/wiki_contributor_guide/agent.ts";
import * as module_17 from "../../agent/subagents/wiki_failure_analyst/agent.ts";
import * as module_18 from "../../agent/subagents/wiki_historian/agent.ts";
import * as module_19 from "../../agent/subagents/wiki_maintainer_profiler/agent.ts";
import * as module_20 from "../../agent/subagents/wiki_pitfall_mapper/agent.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "tools/diff_parser.ts": module_1,
                  "tools/github_fetcher.ts": module_2,
                  "tools/markdown_exporter.ts": module_3,
                  "tools/memory_consistency_checker.ts": module_4,
                  "tools/repository_scanner.ts": module_5,
                  "tools/review_analyzer.ts": module_6,
                  "tools/timeline_generator.ts": module_7
                })
            }),
      "subagents/assumption_hunter": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_8
                })
            }),
      "subagents/knowledge_validator": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_9
                })
            }),
      "subagents/maintainer": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_10
                })
            }),
      "subagents/mergeability_gate": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_11
                })
            }),
      "subagents/pr_reviewer": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_12
                })
            }),
      "subagents/repo_expert": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_13
                })
            }),
      "subagents/test_gap": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_14
                })
            }),
      "subagents/wiki_architect": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_15
                })
            }),
      "subagents/wiki_contributor_guide": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_16
                })
            }),
      "subagents/wiki_failure_analyst": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_17
                })
            }),
      "subagents/wiki_historian": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_18
                })
            }),
      "subagents/wiki_maintainer_profiler": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_19
                })
            }),
      "subagents/wiki_pitfall_mapper": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_20
                })
            })
    })
});

export default moduleMap;
